
import React from 'react';

interface PlaceholderAppContentProps {
  appName: string;
  prompt?: string;
}

const PlaceholderAppContent: React.FC<PlaceholderAppContentProps> = ({ appName, prompt = "hesap makinesi" }) => {
  return (
    <div className="p-6 text-sm">
      <h2 className="text-xl font-semibold mb-3">{appName}</h2>
      <p className="mb-2">
        Generated from prompt: "{prompt}"
      </p>
      <p>
        This is a placeholder app. In the full implementation, this content would be generated by AI or provide specific app functionality.
      </p>
      <img src="https://picsum.photos/300/200" alt="Placeholder" className="mt-4 rounded-md shadow-lg" />
    </div>
  );
};

export default PlaceholderAppContent;
